# Generated by Django 5.0.3 on 2024-05-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censorship',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='censorship',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='censorship',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('Vulgar', 'Vulgar'), ('Spam', 'Spam')], max_length=8, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='report',
            name='option',
            field=models.CharField(choices=[('Selesai', 'Selesai'), ('Tinjau', 'Tinjau')], default='Tinjau', max_length=8, verbose_name='option'),
        ),
    ]
