# Generated by Django 5.0.3 on 2024-07-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('Vulgar', 'Vulgar'), ('Spam', 'Spam'), ('Slur', 'Slur'), ('Other', 'Other')], max_length=8, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
