# Generated by Django 4.2.7 on 2024-02-01 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='report',
            table='Report',
        ),
    ]
