# Generated by Django 4.2.7 on 2024-02-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_report_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('Vulgar', 'Vulgar'), ('Spam', 'Spam')], max_length=8),
        ),
    ]
