# Generated by Django 5.0.3 on 2024-08-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_report_category_alter_report_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
    ]
