# Generated by Django 5.0.3 on 2024-05-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_censorship_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='censorship',
            options={'verbose_name': 'censorship', 'verbose_name_plural': 'censorships'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'report', 'verbose_name_plural': 'reports'},
        ),
        migrations.AlterModelTable(
            name='censorship',
            table=None,
        ),
        migrations.AlterModelTable(
            name='censorshiptranslation',
            table='database_censorship_translation',
        ),
        migrations.AlterModelTable(
            name='report',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reporttranslation',
            table='database_report_translation',
        ),
    ]
