# Generated by Django 4.2.7 on 2024-02-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_report_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='option',
            field=models.CharField(choices=[('Vulgar', 'Vulgar'), ('Spam', 'Spam')], default='Tinjau', max_length=8),
        ),
    ]
