# Generated by Django 4.2.7 on 2024-02-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_report_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='option',
            field=models.CharField(choices=[('Selesai', 'Selesai'), ('Tinjau', 'Tinjau')], default='Tinjau', max_length=8),
        ),
    ]
