# Generated by Django 4.2.7 on 2024-02-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_report_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Censorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'Word Censorship',
            },
        ),
    ]
