# Generated by Django 4.2.7 on 2023-11-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=120)),
                ('definition', models.TextField()),
                ('up', models.IntegerField()),
                ('down', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
    ]
