# Generated by Django 4.2.7 on 2024-01-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='rating',
        ),
        migrations.AlterField(
            model_name='word',
            name='down',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='up',
            field=models.IntegerField(default=0),
        ),
    ]
