# Generated by Django 5.0.3 on 2024-04-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_alter_word_pronunciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Hidden', 'Hidden'), ('Vulgar', 'Vulgar')], default='Public', max_length=8),
        ),
    ]
