# Generated by Django 4.2.7 on 2024-01-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_remove_word_rating_alter_word_down_alter_word_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
