# Generated by Django 5.0.3 on 2024-05-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_word_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronounce',
            name='name',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pronounce',
            name='pronunciation',
            field=models.FileField(blank=True, null=True, upload_to='pronunciation/', verbose_name='pronunciation'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.TextField(verbose_name='definition'),
        ),
        migrations.AlterField(
            model_name='word',
            name='down',
            field=models.IntegerField(default=0, verbose_name='down'),
        ),
        migrations.AlterField(
            model_name='word',
            name='up',
            field=models.IntegerField(default=0, verbose_name='up'),
        ),
        migrations.AlterField(
            model_name='word',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='word',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Hidden', 'Hidden'), ('Vulgar', 'Vulgar')], default='Public', max_length=8, verbose_name='visibility'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=120, verbose_name='word'),
        ),
    ]
