# Generated by Django 5.0.3 on 2024-05-13 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_alter_pronounce_name_alter_pronounce_pronunciation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pronounce',
            options={'verbose_name': 'pronounce', 'verbose_name_plural': 'pronounces'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': 'word', 'verbose_name_plural': 'words'},
        ),
        migrations.AlterModelTable(
            name='word',
            table=None,
        ),
    ]
