# Generated by Django 4.2.7 on 2024-01-14 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_tags_word_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
