# Generated by Django 4.2.7 on 2024-01-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0006_rename_tags_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='pronunciation',
            field=models.FileField(blank=True, null=True, upload_to='pronunciation/'),
        ),
        migrations.AlterModelTable(
            name='word',
            table='Word',
        ),
    ]
