# Generated by Django 4.2.7 on 2024-01-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0007_word_pronunciation_alter_word_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='tags',
        ),
        migrations.AddField(
            model_name='word',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='word_tag', to='word.tag'),
        ),
    ]
